//user
export const LOGOUT = 'LOGOUT';
export const STORE_SAVE_ACCOUNT = 'STORE_SAVE_ACCOUNT';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const STORE_UPDATE_ACCOUNT = 'STORE_UPDATE_ACCOUNT';

//ticket
export const STORE_USER_TICKET_LIST = 'STORE_USER_TICKETS_LIST';
export const STORE_TICKET_ITEM = 'STORE_TICKET_ITEM';
export const STORE_TICKET_LIST = 'STORE_TICKET_LIST';

//error
export const ADD_ERROR_ITEM = 'ADD_ERROR_ITEM';
export const ERROR_CLEAR = 'ERROR_CLEAR';